Backend1/Models/CalcServiceViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Backend1.Models
{
    public class CalcServiceViewModel
    {
        public double ValFst { get; set; }
        public double ValSec { get; set; }

        public double ValA { get; set; }
        public double ValS { get; set; }
        public double ValM { get; set; }
        public double ValD { get; set; }
    }
}

Backend1/Models/DateTimeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Backend1.Models
{
    public class DateTimeViewModel
    {
        public DateTime Current { get; set; }
    }
}

Backend1/Controllers/CalcServiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Backend1.Models;
using Backend1.Services;

namespace Backend1.Controllers
{
    public class CalcServiceController : Controller
    {
        private ICalcService CalcService;
        private IRandomValService RandomService;

        public CalcServiceController(ICalcService par, IRandomValService par2)
        {
            CalcService = par;
            RandomService = par2;
        }


        public IActionResult AccessServiceDirectly()
        {

            return this.View(); 
        }

        public IActionResult PassUsingModel()
        {
            var fst = RandomService.GetRandomVal(0, 10);
            var sec = RandomService.GetRandomVal(0, 10);
            var a = CalcService.CalcAdd(fst,sec);
            var s = CalcService.CalcSub(fst, sec);
            var m = CalcService.CalcMult(fst, sec);
            var d = CalcService.CalcDiv(fst, sec);
            var model = new CalcServiceViewModel
            {
                ValFst = fst,
                ValSec = sec,
                ValA = a,
                ValS = s,
                ValM = m,
                ValD = d
            };

            return this.View(model);
        }

        public IActionResult PassUsingViewBag()
        {
            var fst = RandomService.GetRandomVal(0, 10);
            var sec = RandomService.GetRandomVal(0, 10);
            var a = CalcService.CalcAdd(fst, sec);
            var s = CalcService.CalcSub(fst, sec);
            var m = CalcService.CalcMult(fst, sec);
            var d = CalcService.CalcDiv(fst, sec);

            this.ViewBag.ValFst = fst;
            this.ViewBag.ValSec = sec;
            this.ViewBag.ValA = a;
            this.ViewBag.ValS = s;
            this.ViewBag.ValM = m;
            this.ViewBag.ValD = d;

            return this.View();
        }

        public IActionResult PassUsingViewData()
        {
            var fst = RandomService.GetRandomVal(0, 10);
            var sec = RandomService.GetRandomVal(0, 10);
            var a = CalcService.CalcAdd(fst, sec);
            var s = CalcService.CalcSub(fst, sec);
            var m = CalcService.CalcMult(fst, sec);
            var d = CalcService.CalcDiv(fst, sec);

            this.ViewData["ValFst"] = fst;
            this.ViewData["ValSec"] = sec;
            this.ViewData["ValA"] = a;
            this.ViewData["ValS"] = s;
            this.ViewData["ValM"] = m;
            this.ViewData["ValD"] = d;

            return this.View();
        }
    }
}

Backend1/Controllers/DateTimeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Backend1.Models;
using Backend1.Services;
using Microsoft.AspNetCore.Mvc;

namespace Backend1.Controllers
{
    public class DateTimeController : Controller
    {
        private readonly IDateTimeService dataTimeService;

        public DateTimeController(IDateTimeService dataTimeService)
        {
            this.dataTimeService = dataTimeService;
        }

        public ActionResult PassUsingViewData()
        {
            var current = this.dataTimeService.Now;
            this.ViewData["Current"] = current;

            return this.View();
        }

        public ActionResult PassUsingViewBag()
        {
            var current = this.dataTimeService.Now;
            this.ViewBag.Current = current;

            return this.View();
        }

        public ActionResult PassUsingModel()
        {
            var current = this.dataTimeService.Now;
            var model = new DateTimeViewModel
            {
                Current = current
            };

            return this.View(model);
        }

        public ActionResult AccessServiceDirectly()
        {
            return this.View();
        }
    }
}

Backend1/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Backend1.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return this.View();
        }

        public IActionResult Error()
        {
            return this.View();
        }
    }
}

Backend1/Views/CalcService/AccessServiceDirectly.cshtml
@using Backend1.Services;
@inject ICalcService CalcService;
@inject IRandomValService RandomValService;
@{
    ViewData["Title"] = "AccessServiceDirectly";
}

<h2>AccessServiceDirectly</h2>

@{
    var f = @RandomValService.GetRandomVal(0, 10);
    var sec = @RandomValService.GetRandomVal(0, 10);
    var a = @CalcService.CalcAdd(f, sec);
    var s = @CalcService.CalcSub(f, sec);
    var m = @CalcService.CalcMult(f, sec);
    var d = @CalcService.CalcDiv(f, sec);
 }


<dl>
    <dt>Rand Value First : @f</dt>
    <dt>Rand Value Second : @sec</dt>

    <dt>Add :</dt>
    <dd>@f + @sec = @a</dd>
    <dt>Sub :</dt>
    <dd>@f - @sec = @s</dd>
    <dt>Mult :</dt>
    <dd>@f * @sec = @m</dd>
    <dt>Div :</dt>
    <dd>@f / @sec = @d</dd>
</dl>

Backend1/Views/CalcService/PassUsingModel.cshtml
@model Backend1.Models.CalcServiceViewModel
@{
    ViewData["Title"] = "PassUsingModel";
}

<h2>PassUsingModel</h2>
<dl>
        <dt>Rand Value First : @Model.ValFst</dt>
        <dt>Rand Value Second : @Model.ValSec</dt>
 
    <dt>Add :</dt>
    <dd>@Model.ValFst + @Model.ValSec = @Model.ValA</dd>
    <dt>Sub :</dt>
    <dd>@Model.ValFst - @Model.ValSec = @Model.ValS</dd>
    <dt>Mult :</dt>
    <dd>@Model.ValFst * @Model.ValSec = @Model.ValM</dd>
    <dt>Div :</dt>
    <dd>@Model.ValFst / @Model.ValSec = @Model.ValD</dd>
</dl>

Backend1/Views/CalcService/PassUsingViewBag.cshtml
@{
    ViewData["Title"] = "PassUsingViewBag";
}

<h2>PassUsingViewBag</h2>

<dl>
    <dt>Rand Value First : @ViewBag.ValFst</dt>
    <dt>Rand Value Second : @ViewBag.ValSec</dt>

    <dt>Add :</dt>
    <dd>@ViewBag.ValFst + @ViewBag.ValSec = @ViewBag.ValA</dd>
    <dt>Sub :</dt>
    <dd>@ViewBag.ValFst - @ViewBag.ValSec = @ViewBag.ValS</dd>
    <dt>Mult :</dt>
    <dd>@ViewBag.ValFst * @ViewBag.ValSec = @ViewBag.ValM</dd>
    <dt>Div :</dt>
    <dd>@ViewBag.ValFst / @ViewBag.ValSec = @ViewBag.ValD</dd>
</dl>

Backend1/Views/CalcService/PassUsingViewData.cshtml
@{
    ViewData["Title"] = "PassUsingViewData";
}

<h2>PassUsingViewData</h2>


<dl>
    <dt>Rand Value First : @ViewData["ValFst"]</dt>
    <dt>Rand Value Second : @ViewData["ValSec"]</dt>

    <dt>Add :</dt>
    <dd>@ViewData["ValFst"] + @ViewData["ValSec"] = @ViewData["ValA"]</dd>
    <dt>Sub :</dt>
    <dd>@ViewData["ValFst"] - @ViewData["ValSec"] = @ViewData["ValS"]</dd>
    <dt>Mult :</dt>
    <dd>@ViewData["ValFst"] * @ViewData["ValSec"] = @ViewData["ValM"]</dd>
    <dt>Div :</dt>
    <dd>@ViewData["ValFst"] / @ViewData["ValSec"] = @ViewData["ValD"]</dd>
</dl>

Backend1/Views/DateTime/AccessServiceDirectly.cshtml
@using Backend1.Services
@model dynamic
@inject IDateTimeService DateTimeService
@{
    ViewBag.Title = "Access service directly";
}

<h2>Current Date & Time</h2>
<dl class="dl-horizontal">
    <dt>IDateTimeService.Now</dt>
    <dd>@DateTimeService.Now</dd>
</dl>

Backend1/Views/DateTime/PassUsingModel.cshtml
@model Backend1.Models.DateTimeViewModel
@{
    ViewBag.Title = "Pass using Model";
}

<h2>Current Date & Time</h2>
<dl class="dl-horizontal">
    <dt>Model.Current</dt>
    <dd>@Model.Current</dd>
</dl>

Backend1/Views/DateTime/PassUsingViewBag.cshtml
@model dynamic
@{
    ViewBag.Title = "Pass using ViewBag";
}

<h2>Current Date & Time</h2>
<dl class="dl-horizontal">
    <dt>ViewBag.Current</dt>
    <dd>@ViewBag.Current</dd>
</dl>

Backend1/Views/DateTime/PassUsingViewData.cshtml
@model dynamic
@{
    ViewBag.Title = "Pass using ViewData";
}

<h2>Current Date & Time</h2>
<dl class="dl-horizontal">
    <dt>ViewData["Current"]</dt>
    <dd>@ViewData["Current"]</dd>
</dl>

Backend1/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<h2>Calc Service Demonstration</h2>
<ul>
    <li><a asp-controller="CalcService" asp-action="PassUsingModel">Using Model Calc</a></li>
    <li><a asp-controller="CalcService" asp-action="PassUsingViewData">Using ViewData Calc</a></li>
    <li><a asp-controller="CalcService" asp-action="PassUsingViewBag">Using ViewBag Calc</a></li>
    <li><a asp-controller="CalcService" asp-action="AccessServiceDirectly">Using Service Injection Calc</a></li>
</ul>

Backend1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Backend1</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Backend1</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - Backend1</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>